// This File Was Generated By The Fractal Tree Lesson Compiler (mkall.py)

// This File Was Generated By The Fractal Tree Lesson Compiler (mklesson.py)

window.lessonList = [];
window.compiledCourse_python_intro_ar = {"id": "python_intro", "lang": "ar", "name": "Intro To Python", "description": "Learn the very basics of Python 3, no prior coding knowledge required.", "icon": "Python.webp", "segments": []};

window.lessonList.push(window.compiledCourse_python_intro_ar);

window.compiledCourse_python_intro_en = {"id": "python_intro", "lang": "en", "name": "Intro To Python", "description": "Learn the very basics of Python 3, no prior coding knowledge required.", "icon": "Python.webp", "segments": ["# Placeholder 1\nPineapple on pizza is very good, idk why ppl hate it", "# Placeholder 2\nCoke zero > regular coke > pepsi"]};

window.lessonList.push(window.compiledCourse_python_intro_en);


window.doneInitStep()